module.exports = {
  someSidebar: {
    JavaScript: [
      'JavaScript/1、数据类型、转换、拷贝',
      'JavaScript/2、原型和原型链',
      'JavaScript/3、执行上下文、this和闭包',
      'JavaScript/4、继承',
      'JavaScript/5、防抖和节流',
      'JavaScript/6、数组、字符串常用方法',
      'JavaScript/7、Set和Map数据结构',
      'JavaScript/8、Promise专题',
      'JavaScript/9、eventloop事件机制',
      'JavaScript/10、函数、箭头函数',
      'JavaScript/11、异步的历史及相关问答',
      'JavaScript/12、各种手写',
      'JavaScript/13、内存机制',
      'JavaScript/14、事件流（冒泡和捕获）',
      'JavaScript/15、ES6的Class',
      'JavaScript/16、let和const',
      'JavaScript/17、错误处理',
      'JavaScript/18、操作符及优先级',
      'JavaScript/19、ES新特性及原理',
      'JavaScript/20、函数式编程',
      'JavaScript/Typescript笔记',
    ],
    CSS: [
      'CSS/1、选择器和优先度',
      'CSS/2、浮动和清除浮动',
      'CSS/3、盒子模型',
      'CSS/4、flex布局',
      'CSS/5、层叠上下文',
      'CSS/6、品字、圣杯、双飞翼布局',
      'CSS/7、垂直水平居中的方法',
      'CSS/8、display、定位',
      'CSS/9、像素和viewport',
      'CSS/10、padding、margin',
      'CSS/11、BFC',
      'CSS/12、transform',
      'CSS/13、可以继承的CSS属性盘点',
      'CSS/14、opacity、visibility、display',
    ],
    浏览器: [
      'Browser/1、缓存策略，协商缓存和强缓存',
      'Browser/2、页面渲染的过程',
      'Browser/3、浏览器的本地存储',
      'Browser/4、页面性能优化',
      'Browser/5、安全方面',
      'Browser/6、回流与重绘',
      'Browser/7、浏览器工作原理',
      'Browser/8、cookie和Same Site',
      'Browser/9、前端路由及原理',
      'Browser/10、跨域',
    ],
    HTTP: [
      'HTTP/1、http基础',
      'HTTP/2、http缓存机制',
      'HTTP/3、TCP',
      'HTTP/4、fetch和axios',
      'HTTP/5、http版本更迭',
    ],
    React: [
      'React/生命周期',
      'React/Class组件和function组件',
      'React/diff',
      'React/fiber',
      'React/hook',
      'React/redux',
      'React/setState',
      'React/Virtual DOM',
    ],
    Webpack: [
      'Webpack/1、基本概念'
    ],
    Docusaurus: ['doc1', 'doc2', 'doc3'],
    // Features: ['mdx'],
  },
};
